name: Xbox

on: [push, pull_request]

jobs:
  Xbox:
    runs-on: ubuntu-latest

    steps:
    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld llvm python3-pip qemu-utils
        pip3 install --upgrade pip
        pip3 install pyfatx libqcow-python

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile nxdk
      run: |
        git clone --recursive https://github.com/XboxDev/nxdk.git
        eval $(nxdk/bin/activate -s)
        cd nxdk
        make NXDK_ONLY=y CFLAGS=-O2 CXXFLAGS=-O2
        make tools
        cd ..

    - name: Compile program
      run: |
        eval $(nxdk/bin/activate -s)
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=nxdk/share/toolchain-nxdk.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        cd ..

    - name: Generate HDD Image
      run: |
        mkdir c
        cp build/default.xbe c/xboxdash.xbe
        python3 scripts/create_hdd_image.py c -o xbox_hdd.img
        qemu-img convert -f raw -O qcow2 -c xbox_hdd.img xbox_hdd.qcow2
        rm xbox_hdd.img

    - name: Prepare artifact
      run: |
        mkdir -p artifact
        mv xbox_hdd.qcow2 artifact/xbox_hdd.qcow2
        mv build/xemu_menu.iso artifact/xemu_menu.iso
        mv build/default.xbe artifact/default.xbe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: xemu_menu
        path: artifact
