name: Xbox

on: [push, pull_request]

jobs:
  Xbox:
    runs-on: ubuntu-latest

    steps:
    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y python3-pip qemu-utils
        pip3 install --upgrade pip
        pip3 install pyfatx libqcow-python

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile program
      run: |
        docker run --rm \
          -u $(id -u):$(id -g) \
          -v "$(pwd)":/workspace -w /workspace \
          ghcr.io/xboxdev/nxdk:latest \
          sh -c "mkdir -p build && cd build && \
                cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/src/nxdk/share/toolchain-nxdk.cmake -DCMAKE_BUILD_TYPE=Release && \
                cmake --build ."

    - name: Generate HDD Image
      run: |
        mkdir c
        cp build/default.xbe c/xboxdash.xbe
        python3 scripts/create_hdd_image.py c -o xbox_hdd.img
        qemu-img convert -f raw -O qcow2 -c xbox_hdd.img xbox_hdd.qcow2
        rm xbox_hdd.img

    - name: Prepare artifact
      run: |
        mkdir -p artifact
        mv xbox_hdd.qcow2 artifact/xbox_hdd.qcow2
        mv build/xemu_menu.iso artifact/xemu_menu.iso
        mv build/default.xbe artifact/default.xbe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: xemu_menu
        path: artifact
